name: Deploy to Dev Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: IgorNadj/github-actions@main
        with:
          ssh-private-key: ${{ secrets.DEV_SERVER_SSH_KEY }}
